
### 유저 생성
POST localhost:8080/api/users
Content-Type: application/json

{
  "email": "user123@gmail.com",
  "password": "password",
  "status": {
    "status": "WITHDRAWN"
  },
  "userId": "user123"
}

### 유저 수정
PUT localhost:8080/api/users
Content-Type: application/json

{
  "userId": "user210",
  "status": {
    "status": "DORMANT"
  }
}

### 유저 삭제
DELETE localhost:8080/api/users
Content-Type: application/json

{
  "userId": "user12"
}

### 유저 로그인 검증
POST localhost:8080/api/users/login
Content-Type: application/json

{
  "userId": "user2101",
  "password": "password"
}
