
### 유저 생성
POST localhost:8080/api/users
Content-Type: application/json

{
  "email": "user1@gmail.com",
  "password": "password",
  "status": {
    "status": "REGISTERED"
  },
  "userId": "1user5120"
}

### 유저 수정
PUT localhost:8080/api/users
Content-Type: application/json

{
  "userId": "1user5120",
  "status": {
    "status": "DORMANT"
  }
}

### 유저 삭제
DELETE localhost:8080/api/users
Content-Type: application/json

{
  "userId": "1user5120"
}

