
### 유저 생성
POST localhost:8081/api/users
Content-Type: application/json

{
  "email": "user123@gmail.com",
  "password": "password",
  "status": {
    "status": "REGISTERED"
  },
  "userId": "user21201"
}

### 유저 수정
PUT localhost:8081/api/users
Content-Type: application/json

{
  "userId": "user210",
  "status": {
    "status": "DORMANT"
  }
}

### 유저 삭제
DELETE localhost:8081/api/users
Content-Type: application/json

{
  "userId": "user210"
}

### 로그인 검증
POST localhost:8081/api/users/login
Content-Type: application/json

{
  "userId": "user2120",
  "password": "password"
}

### 로그인 검증
POST localhost:8081/api/users/login
Content-Type: application/json

{
  "userId": "test1",
  "password": "password"
}
