spring:
  datasource:
    url: jdbc:mysql://s4.java21.net:13306/nhn_academy_107
    username: nhn_academy_107
    password: uS6erwkb!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true
        ddl-auto: update


logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.transaction.interceptor: trace


